import os

class_names = [
        'AMONG_US', 'CONTRA', 'DEATH_STRANDING', 'ELDEN_RING', 'GOD_OF_WAR_1', 
        'GOD_OF_WAR_2018', 'GTA_SAN_ANDREAS', 'GTA_V', 'HADES', 'HOLLOW_KNIGHT', 
        'HORIZON_FORBBIDEN_WEST', 'HORIZON_ZERO_DAWN', 'MARIO_GALAXY', 'MARIO_KART_8', 
        'MARIO_KART_WORLD', 'MARIO_ODYSSEY', 'MINECRAFT', 'NEW_SUPER_MARIO_BROS', 
        'POKEMON_EMERALD', 'POKEMON_RED', 'POKEMON_X_Y', 'PUNCH_OUT_NES', 
        'RED_DEAD_REDEMPTION_1', 'RED_DEAD_REDEMPTION_2', 'SILENT_HILL_2', 
        'SILKSONG', 'STRAY', 'SUPER_MARIO_64', 'SUPER_MARIO_BROS', 
        'SUPER_MARIO_BROS_WONDER', 'UNDERTALE'
    ]

for classl in class_names:
    os.mkdir(f"./{classl}")